### ISSUE TITLE
Error With GetStartPoint

### ISSUE THREAD

**Issue by Albiwalbi** [shellljx/SnowLayout#1]
Hi,

I've included your library in my app as a small easter egg, but a lot of users are getting this error:

`com.licrafter.snowlayout.library.SnowLayout.getStartPoint (SnowLayout.java:189)
com.licrafter.snowlayout.library.SnowLayout.generateSnow (SnowLayout.java:89)
com.licrafter.snowlayout.library.SnowLayout.access$000 (SnowLayout.java:27)
com.licrafter.snowlayout.library.SnowLayout$1.run (SnowLayout.java:63)`

Does anyone have a solution? The library works just fine, but only some times it doesn't. Thanks!

**Comment by shellljx** [comment]
Is there any other more error message?

**Comment by Albiwalbi** [comment]
Yes, Sorry. Here is the full crashlog that I could receive from crashlytics. Hope you can fix it :) Small note: I was using version 1.0, maybe it was fixed in that release.

`Fatal Exception: java.lang.IllegalArgumentException
n must be positive
java.util.Random.nextInt (Random.java:391)
arrow_right
com.licrafter.snowlayout.library.SnowLayout.getStartPoint (SnowLayout.java:189)
com.licrafter.snowlayout.library.SnowLayout.generateSnow (SnowLayout.java:89)
com.licrafter.snowlayout.library.SnowLayout.access$000 (SnowLayout.java:27)
com.licrafter.snowlayout.library.SnowLayout$1.run (SnowLayout.java:63)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6165)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:888)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:778)`

**Comment by Albiwalbi** [comment]
I've investigated your source code and found out that in some cases getWidth returns a negative int. Probably -1 for not resolved. I'm looking into an solution right now.

**Comment by Albiwalbi** [comment]
Hi, sorry but the issue is not solved by upgrading to version 1.1. 154 users have reported the same issue in the latest update, are you able to fix it?

**Comment by shellljx** [comment]
you can upgrade to v1.1.1 to solve this problem。
